config/routes.rb
Rails.application.routes.draw do

  if Rails.env == 'development'
    require 'sidekiq/web'
    require 'sidekiq-scheduler/web'
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :notifications, only: [:index, :show, :update]
      resources :facilities, only: [:index, :show, :create, :update, :destroy]
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      resources :ota, only: [:index, :show, :create, :update, :destroy]
      resources :ota_rooms, only: [:index, :show, :create, :update, :destroy]
      resources :bookings, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:show, :update, :destroy]
      post      '/ota/:id/crawl/rooms',    to: 'ota#get_rooms'
      post      '/ota/:id/crawl/bookings', to: 'ota#get_bookings'
      get    '/subscribe', to: 'subscribes#show'
      post   '/subscribe', to: 'subscribes#create'
      put    '/subscribe', to: 'subscribes#update'
      patch  '/subscribe', to: 'subscribes#update'
    end
  end

  scope :api, { format: 'json'} do
    scope :v1 do
      devise_for :users, :class_name => 'User', controllers: {
        :registrations => "user/registrations",
        :sessions => "user/sessions",
      }
      devise_scope :user do
        get 'users' => 'api/v1/users#index'
        get 'current_user' => 'api/v1/users#current'
      end
    end
  end

  if Rails.env == 'development'
    mount Sidekiq::Web, at: "/sidekiq"
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :notifications, only: [:index, :show, :create, :update, :destroy]
      resources :facilities, only: [:index, :show, :create, :update, :destroy]
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      resources :ota, only: [:index, :show, :create, :update, :destroy]
      resources :ota_rooms, only: [:index, :show, :create, :update, :destroy]
      resources :bookings, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:show, :update, :destroy]
    end
  end

  namespace :admin do
    devise_for :users, controllers: {
      sessions: "admin/users/sessions",
    }, skip: [:registrations]
    # resources :notifications
    resources :facilities
    resources :rooms
    resources :ota
    # resources :ota_rooms
    # resources :scraping_logs, only: [:index, :show]
    resources :crawl_logs, only: [:index, :show]
    resources :bookings, expect: [:new, :create]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get '/dashboard', to: 'pages#dashboard'
  end

  root :to => "app#index"
  match "*path", to: "app#index", format: false, via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/template_parts/admin/_header.html.slim
.header.navbar.navbar-dark.fixed-top.bg-dark.flex-md-nowrap.p-0.shadow
  = link_to '管理画面', admin_dashboard_path, class: 'navbar-brand col-sm-3 col-md-2 mr-0'
  ul.navbar-nav.px-3
    li.nav-item.text-nowrap
      = link_to 'サービス画面', root_path, class: 'nav-link'

app/views/template_parts/admin/_sidebar.html.slim
ul.nav.flex-column
  li.nav-item
    - activate = ( controller.controller_name == 'static_pages' && controller.action_name == 'dashboard' ) ? ' active' : ''
    = link_to admin_dashboard_path, class: 'nav-link' + activate do
      = icon('fas', 'home')
      | dashboard

h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
  span ユーザー
ul.nav.flex-column.mb-2
  li.nav-item
    - activate = ( controller.controller_name == 'users' ) ? ' active' : ''
    = link_to admin_users_path, class: 'nav-link' + activate do
      = icon('fas', 'user')
      | ユーザー管理
h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
  span コンテンツ
ul.nav.flex-column.mb-2
  li.nav-item
    - activate = ( controller.controller_name == 'facilities' ) ? ' active' : ''
    = link_to admin_facilities_path, class: 'nav-link' + activate do
      = icon('fas', 'store-alt')
      | 施設管理
  li.nav-item
    - activate = ( controller.controller_name == 'rooms' ) ? ' active' : ''
    = link_to admin_rooms_path, class: 'nav-link' + activate do
      = icon('fas', 'door-closed')
      | 部屋管理
  li.nav-item
    - activate = ( controller.controller_name == 'ota' ) ? ' active' : ''
    = link_to admin_ota_path, class: 'nav-link' + activate do
      = icon('fas', 'box')
      | OTA管理
  li.nav-item
    - activate = ( controller.controller_name == 'bookings' ) ? ' active' : ''
    = link_to admin_bookings_path, class: 'nav-link' + activate do
      = icon('fas', 'book')
      | 予約管理

h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
  span システム
ul.nav.flex-column.mb-2
  li.nav-item
    - activate = ( controller.controller_name == 'crawl_logs' ) ? ' active' : ''
    = link_to admin_crawl_logs_path, class: 'nav-link' + activate do
      = icon('fas', 'shoe-prints')
      | クロールログ管理