config/routes.rb
Rails.application.routes.draw do

  if Rails.env == 'development'
    require 'sidekiq/web'
    require 'sidekiq-scheduler/web'
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :notifications, only: [:index, :show, :update]
      resources :facilities, only: [:index, :show, :create, :update, :destroy]
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      resources :ota, only: [:index, :show, :create, :update, :destroy]
      resources :ota_rooms, only: [:index, :show, :create, :update, :destroy]
      resources :bookings, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:show, :update, :destroy]
      post      '/ota/:id/crawl/rooms',    to: 'ota#get_rooms'
      post      '/ota/:id/crawl/bookings', to: 'ota#get_bookings'
      get    '/subscribe', to: 'subscribes#show'
      post   '/subscribe', to: 'subscribes#create'
      put    '/subscribe', to: 'subscribes#update'
      patch  '/subscribe', to: 'subscribes#update'
    end
  end

  scope :api, { format: 'json'} do
    scope :v1 do
      devise_for :users, :class_name => 'User', controllers: {
        :registrations => "user/registrations",
        :sessions => "user/sessions",
      }
      devise_scope :user do
        get 'users' => 'api/v1/users#index'
        get 'current_user' => 'api/v1/users#current'
      end
    end
  end

  if Rails.env == 'development'
    mount Sidekiq::Web, at: "/sidekiq"
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :notifications, only: [:index, :show, :create, :update, :destroy]
      resources :facilities, only: [:index, :show, :create, :update, :destroy]
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      resources :ota, only: [:index, :show, :create, :update, :destroy]
      resources :ota_rooms, only: [:index, :show, :create, :update, :destroy]
      resources :bookings, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:show, :update, :destroy]
    end
  end

  namespace :admin do
    devise_for :users, controllers: {
      sessions: "admin/users/sessions",
    }, skip: [:registrations]
    # resources :notifications
    resources :facilities
    resources :rooms
    resources :ota
    # resources :ota_rooms
    # resources :scraping_logs, only: [:index, :show]
    resources :crawl_logs, only: [:index, :show]
    resources :bookings, expect: [:new, :create]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get '/dashboard', to: 'pages#dashboard'
  end

  root :to => "app#index"
  match "*path", to: "app#index", format: false, via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :ota_room
  has_one :scraping_log
  has_one :otum, through: :ota_room
  has_one :room, through: :ota_room

  validates :uid, presence: true
  validates :status, presence: true
  validates :checkin, presence: true
  validates :checkout, presence: true
  validates :count_room, presence: true

  # is_block=trueのときは以下をスルー
  with_options unless: :is_blocked? do
    validates :price, presence: true
    validates :price_balance, presence: true
    validates :price_total, presence: true
    validates :subscriber_name, presence: true, allow_blank: true
    validates :guest_name, presence: true
    validates :number_total, presence: true,
              numericality: {
                only_integer: true,
                greater_than: 0
              }
  end

  # enum
  enum status: [:active, :canceled], _suffix: true

  before_validation :set_defaults

  def set_defaults
    if self.price.blank?
      self.price = 0.0
    end
    # 金額
    if self.price_balance.blank?
      self.price_balance = 0.0
    end
    self.price_total = self.price + self.price_balance
    # 通貨
    if self.currency.blank?
      self.currency = 'yen-ja'
    end

    # 宿泊者情報
    if self.guest_name.blank?
      self.guest_name = self.subscriber_name
    end

    # 予約日
    if self.booking_date.blank?
      self.booking_date = Time.now
    end

    # uid
    if self.uid.blank?
      self.uid = SecureRandom.base64(32)
    end

    # uid
    if self.count_room.blank?
      self.count_room = 1
    end
  end

  def blocked?
    user = self.otum.user
    user.all_bookings.blocked_during(self.checkin, self.checkout).exists?
  end

end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < Admin::ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.page(params[:page]).per(20)
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to [:admin, @booking], notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    if @booking.update(booking_params)
      redirect_to [:admin, @booking], notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    redirect_to admin_bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:uid, :status, :checkin, :checkout, :count_room, :price, :price_balance, :price_total, :subscriber_name, :subscriber_kana, :subscriber_tel, :subscriber_email, :subscriber_address, :booking_date, :guest_name, :guest_kana, :payment_method, :number_total, :number_males, :number_females, :number_adults, :number_children, :currency, :ota_room)
    end
end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < Api::V1::ApplicationController
  before_action :set_booking, only: [:show, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  # GET /api/v1/bookings
  # GET /api/v1/bookings?year={:year}&month={:month}
  def index
    bookings = Array.new

    if params[:year].nil? || params[:month].nil?
      # パラメータが不足している場合は全て返す
      current_user.ota.each do |otum|
        bookings.concat(otum.bookings)
      end
    else
      year = params[:year].to_i
      month = params[:month].to_i

      # 不正な引数の場合
      if year == 0 || month == 0
        response = {
          status: 'BadRequest',
          message: 'invalid params'
        }
        return render json: response, status: 400
      end

      # 配列を結合
      date_from = Date.new(year, month, 1)
      date_to = Date.new(year, month + 1, 1)
      current_user.ota.each do |otum|
        bookings.concat(
          otum.bookings.select do |booking|
            booking.checkin < date_to && booking.checkout >= date_from
          end
        )
      end
    end

    render json: {
      status: 'Success',
      message: '',
      bookings: bookings.as_json(except: [
        :created_at,
        :updated_at
      ], include: [
        room: {
          include: [
            facility: {
              except: [
                :stripe_subscription_id
              ]
            }
          ]
        },
        otum: {
          except: [
            :password,
            :token,
            :created_at,
            :updated_at
          ], include: [
            facility: {
              except: [
                :stripe_subscription_id
              ]
            }
          ]
        }
      ])
    }, status: 200
  end

  # GET /api/v1/bookings/1
  def show
    # 自分の施設以外だとリジェクト
    if current_user.id != @booking.otum.user.id
      response = {
        status: 'NotFound',
        message: 'booking not found'
      }
      return render json: response, status: 404
    end

    render json: {
      status: 'Success',
      message: '',
      booking: @booking.as_json(except: [
        :created_at,
        :updated_at
      ], include: [
        room: {
          include: [
            facility: {
              except: [
                :stripe_subscription_id
              ]
            }
          ]
        },
        otum: {
          except: [
            :password,
            :token,
            :created_at,
            :updated_at
          ], include: [
            facility: {
              except: [
                :stripe_subscription_id
              ]
            }
          ]
        }
      ])
    }, status: 200
  end

  # POST /api/v1/bookings
  def create
    ota_room = nil
    if(params['booking']['room_id'])
      room = Room.find_by(id: params['booking']['room_id'].to_i)
      if room && room.facility
        otum = room.facility.ota.select do |otum|
          otum.provider == 'default'
        end
        if otum.blank?
          response = {
            status: 'BadRequest',
            message: 'ota id is not exists'
          }
          return render json: response, status: 400
        end
        ota_room = otum[0].ota_rooms.select do |ota_room|
          ota_room.room.id == room.id
        end
        if ota_room.blank?
          response = {
            status: 'BadRequest',
            message: 'ota room id is not exists'
          }
          return render json: response, status: 400
        end
        params['booking']['ota_room_id'] = ota_room[0].id
      else
        response = {
          status: 'BadRequest',
          message: 'room id is not exists'
        }
        return render json: response, status: 400
      end
    else
      response = {
        status: 'BadRequest',
        message: 'room id is not exists'
      }
      return render json: response, status: 400
    end

    @booking = Booking.new(booking_params)

    # OtaRoomの所有者チェック
    ota_room = OtaRoom.find(@booking.ota_room_id)
    if ota_room.otum.user.id != current_user.id
      response = {
        status: 'BadRequest',
        message: 'fail to create booking'
      }
      return render json: response, status: 400
    end

    # ブロックされていないかをチェック
    blocked_booking = Array.new
    current_user.ota.each do |otum|
      blocked_booking.concat(
        otum.bookings.select do |booking|
          booking.checkin < @booking.checkout && booking.checkout >= @booking.checkin && booking.is_blocked
        end
      )
    end
    unless blocked_booking.blank?
      response = {
        status: 'BadRequest',
        message: 'blocked schedule'
      }
      return render json: response, status: 400
    end

    if @booking.save
      render json: {
        status: 'Success',
        message: '',
        booking: @booking.as_json(except: [
          :created_at,
          :updated_at
        ], include: [
          room: {
            include: [
              facility: {
                except: [
                  :stripe_subscription_id
                ]
              }
            ]
          },
          otum: {
            except: [
              :password,
              :token,
              :created_at,
              :updated_at
            ], include: [
              facility: {
                except: [
                  :stripe_subscription_id
                ]
              }
            ]
          }
        ])
      }, status: 201
    else
      response = {
        status: 'BadRequest',
        message: 'fail to create booking'
      }
      render json: response, status: 400
    end
  end

  # PATCH/PUT /api/v1/bookings/1
  def update
    # 自分の施設以外だとリジェクト
    if current_user.id != @booking.otum.user.id
      response = {
        status: 'NotFound',
        message: 'booking not found'
      }
      return render json: response, status: 404
    end

    # ブロックされていないかをチェック
    blocked_booking = Array.new
    current_user.ota.each do |otum|
      blocked_booking.concat(
        otum.bookings.select do |booking|
          booking.checkin < @booking.checkout && booking.checkout >= @booking.checkin && booking.is_blocked
        end
      )
    end
    unless blocked_booking.blank?
      response = {
        status: 'BadRequest',
        message: 'blocked schedule'
      }
      return render json: response, status: 400
    end

    if @booking.update(booking_params)
      render json: {
        status: 'Success',
        message: '',
        booking: @booking.as_json(except: [
          :created_at,
          :updated_at
        ], include: [
          room: {
            include: [
              facility: {
                except: [
                  :stripe_subscription_id
                ]
              }
            ]
          },
          otum: {
            except: [
              :password,
              :token,
              :created_at,
              :updated_at
            ], include: [
              facility: {
                except: [
                  :stripe_subscription_id
                ]
              }
            ]
          }
        ])
      }, status: 201
    else
      response = {
        status: 'BadRequest',
        message: 'fail to update booking'
      }
      render json: response, status: 400
    end
  end

  # DELETE /api/v1/bookings/1
  def destroy
    # 自分の施設以外だとリジェクト
    if current_user.id != @booking.otum.user.id
      response = {
        status: 'NotFound',
        message: 'booking not found'
      }
      return render json: response, status: 404
    end

    @booking.destroy
    response = {
      status: 'Success',
      message: ''
    }
    render json: response, status: 200
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:uid, :status, :checkin, :checkout, :count_room, :price, :price_balance, :price_total, :subscriber_name, :subscriber_kana, :subscriber_tel, :subscriber_email, :subscriber_address, :booking_date, :guest_name, :guest_kana, :payment_method, :number_total, :number_males, :number_females, :number_adults, :number_children, :currency, :ota_room_id, :comment, :is_blocked)
    end
end

app/helpers/admin/bookings_helper.rb
module Admin::BookingsHelper
end

app/views/admin/bookings/_form.html.slim
= form_with(model: [:admin, booking], local: true) do |form|
  - if booking.errors.any?
    #error_explanation
      h2
        = pluralize(booking.errors.count, "error")
        |  prohibited this booking from being saved:
      ul
        - booking.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = form.label :uid
    = form.text_field :uid, class: 'form-control'
  .form-group
    = form.label :status
    = form.select :status, Booking.statuses_i18n.keys.map { |k| [Booking.statuses_i18n[k], k] }, {}, {class: 'form-control'}
  .form-group
    = form.label :checkin
    br
    = form.datetime_select :checkin, {}, class: 'form-control dateselect'
  .form-group
    = form.label :checkout
    br
    = form.date_select :checkout, {}, class: 'form-control dateselect'
  .form-group
    = form.label :count_room
    = form.number_field :count_room, class: 'form-control'
  .form-group
    = form.label :price
    = form.text_field :price, class: 'form-control'
  .form-group
    = form.label :price_balance
    = form.text_field :price_balance, class: 'form-control'
  .form-group
    = form.label :price_total
    = form.text_field :price_total, class: 'form-control'
  .actions
    = form.submit class: 'btn btn-primary'

app/views/admin/bookings/edit.html.slim
h1 予約を編集
= render 'form', booking: @booking
br
div class="btn-group" role="group" aria-label="edit group"
  = link_to '詳細', [:admin, @booking], class: 'btn btn-light'
  = link_to '戻る', admin_bookings_path, class: 'btn btn-secondary'

app/views/admin/bookings/index.html.slim
-if notice
  .alert.alert-primary role="alert"
    = notice
h1 予約
/ .index-new.text-right
  = link_to '新規作成', new_admin_booking_path, class: 'btn btn-success'
table.table
  thead.thead-dark
    tr
      th ID
      th ユーザー
      th OTA
      th 部屋名
      th 予約者名
      th ステータス
      th チェックイン
      th
  tbody
    - @bookings.each do |booking|
      tr
        td = booking.id
        td
          - if booking.otum.user
            = link_to admin_user_path(booking.otum.user) do
              = booking.otum.user.email
        td
          - if booking.otum
            - case(booking.otum.provider)
              - when 'rakuten' then
                = '楽天トラベル'
              - when 'booking' then
                = 'Booking.com'
              - when 'default' then
                = 'VAMOS内部予約管理'
        td
          - if booking.ota_room
            = booking.ota_room.name
        td = booking.subscriber_name
        td = booking.status
        td = booking.checkin.strftime("%Y年%m月%d日")
        td.text-right
          div class="btn-group" role="group" aria-label="index group"
            = link_to '詳細', [:admin, booking], class: 'btn btn-primary btn-sm'
            = link_to '編集', edit_admin_booking_path(booking), class: 'btn btn-light btn-sm'
            = link_to '削除', [:admin, booking], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

= paginate @bookings

app/views/admin/bookings/new.html.slim
h1 予約を新規作成
= render 'form', booking: @booking
br
= link_to 'Back', admin_bookings_path, class: 'btn btn-secondary'

app/views/admin/bookings/show.html.slim
-if notice
  .alert.alert-primary role="alert"
    = notice
h1 予約詳細
table.table.table-striped
  tr
    th #
    td = @booking.id
  tr
    th ユーザー
    td
      - if @booking.otum
        - if @booking.otum.user
          = link_to @booking.otum.user.email, admin_user_path(@booking.otum.user)
  tr
    th OTA
    td
      - if @booking.otum
        - case(@booking.otum.provider)
          - when 'rakuten' then
            = '楽天トラベル'
          - when 'booking' then
            = 'Booking.com'
          - when 'default' then
            = 'VAMOS内部予約管理'
  tr
    th 施設
    td
      - if @booking.otum
        - if @booking.otum.facility
          = link_to @booking.otum.facility.name, admin_facility_path(@booking.otum.facility)
  tr
    th UID
    td = @booking.uid
  tr
    th ステータス
    td = @booking.status
  tr
    th チェックイン日時
    td
      - if @booking.checkin
        = @booking.checkin.strftime("%Y年%m月%d日 %H:%M")
  tr
    th チェックアウト
    td
      - if @booking.checkout
        = @booking.checkout.strftime("%Y年%m月%d日")
  tr
    th 部屋数
    td = @booking.count_room
  tr
    th 価格
    td = @booking.price
  tr
    th 現地支払い金額
    td = @booking.price_balance
  tr
    th 総支払額
    td = @booking.price_total
  tr
    th 予約者名
    td #{@booking.subscriber_name} (#{@booking.subscriber_kana})
  tr
    th 予約者お電話番号
    td = @booking.subscriber_tel
  tr
    th 予約者メールアドレス
    td = @booking.subscriber_email
  tr
    th 予約者ご住所
    td = @booking.subscriber_address
  tr
    th 予約日
    td
      - if @booking.booking_date
        = @booking.booking_date.strftime("%Y年%m月%d日")
  tr
    th 宿泊者名
    td #{@booking.guest_name} (#{@booking.guest_kana})
  tr
    th お支払い方法
    td = @booking.payment_method
  tr
    th 人数
    td #{@booking.number_total}名 (男性#{@booking.number_males}名, 女性#{@booking.number_females}名 / 大人#{@booking.number_adults}名, 子供#{@booking.number_children}名)
  tr
    th 備考
    td = @booking.comment
div class="btn-group" role="group" aria-label="詳細ページメニュー"
  = link_to '編集', edit_admin_booking_path(@booking), class: 'btn btn-primary'
  = link_to '一覧に戻る', admin_bookings_path, class: 'btn btn-secondary'