config/routes.rb
Rails.application.routes.draw do

  if Rails.env == 'development'
    require 'sidekiq/web'
    require 'sidekiq-scheduler/web'
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :notifications, only: [:index, :show, :update]
      resources :facilities, only: [:index, :show, :create, :update, :destroy]
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      resources :ota, only: [:index, :show, :create, :update, :destroy]
      resources :ota_rooms, only: [:index, :show, :create, :update, :destroy]
      resources :bookings, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:show, :update, :destroy]
      post      '/ota/:id/crawl/rooms',    to: 'ota#get_rooms'
      post      '/ota/:id/crawl/bookings', to: 'ota#get_bookings'
      get    '/subscribe', to: 'subscribes#show'
      post   '/subscribe', to: 'subscribes#create'
      put    '/subscribe', to: 'subscribes#update'
      patch  '/subscribe', to: 'subscribes#update'
    end
  end

  scope :api, { format: 'json'} do
    scope :v1 do
      devise_for :users, :class_name => 'User', controllers: {
        :registrations => "user/registrations",
        :sessions => "user/sessions",
      }
      devise_scope :user do
        get 'users' => 'api/v1/users#index'
        get 'current_user' => 'api/v1/users#current'
      end
    end
  end

  if Rails.env == 'development'
    mount Sidekiq::Web, at: "/sidekiq"
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :notifications, only: [:index, :show, :create, :update, :destroy]
      resources :facilities, only: [:index, :show, :create, :update, :destroy]
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      resources :ota, only: [:index, :show, :create, :update, :destroy]
      resources :ota_rooms, only: [:index, :show, :create, :update, :destroy]
      resources :bookings, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:show, :update, :destroy]
    end
  end

  namespace :admin do
    devise_for :users, controllers: {
      sessions: "admin/users/sessions",
    }, skip: [:registrations]
    # resources :notifications
    resources :facilities
    resources :rooms
    resources :ota
    # resources :ota_rooms
    # resources :scraping_logs, only: [:index, :show]
    resources :crawl_logs, only: [:index, :show]
    resources :bookings, expect: [:new, :create]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    get '/dashboard', to: 'pages#dashboard'
  end

  root :to => "app#index"
  match "*path", to: "app#index", format: false, via: :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notificatable, polymorphic: true

  validates :target_type, presence: true
  validates :target_id, presence: true
  validates :profile, presence: true
  validates :status, presence: true
  validates :url, presence: true
  validates :user_id, presence: true

  enum status: [:unread, :read], _suffix: true

  before_validation :set_defaults

  def set_defaults
    if self.status.nil?
      self.status = :unread
    end
  end

end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < Admin::ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.page(params[:page]).per(20)
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    if @notification.save
      redirect_to [:admin, @notification], notice: 'Notification was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    if @notification.update(notification_params)
      redirect_to [:admin, @notification], notice: 'Notification was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    redirect_to admin_notifications_url, notice: 'Notification was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:target_type, :target_id, :type, :status, :url)
    end
end

app/controllers/api/v1/notifications_controller.rb
class Api::V1::NotificationsController < Api::V1::ApplicationController
  before_action :set_notification, only: [:show, :update]
  before_action :authenticate_user!

  # GET /api/v1/notifications
  # GET /api/v1/notifications?unread=[0 or 1]
  def index
    notifications = params[:unread].nil? || params[:unread] == 0 ? current_user.notifications : Notification.where(user: current_user, status: :unread).all

    render json: {
      status: 'Success',
      message: '',
      notifications: notifications.as_json(except: [
        :created_at,
        :updated_at
      ])
    }, status: 200
  end

  # GET /api/v1/notifications/1
  def show
    # 自分の施設以外だとリジェクト
    if current_user.id != @notification.user.id
      response = {
        status: 'NotFound',
        message: 'notification not found'
      }
      return render json: response, status: 404
    end

    render json: {
      status: 'Success',
      message: '',
      notification: @notification.as_json(except: [
        :created_at,
        :updated_at
      ])
    }, status: 200
  end

  # PATCH/PUT /api/v1/notifications/1
  def update
    # 自分の施設以外だとリジェクト
    if current_user.id != @notification.user.id
      response = {
        status: 'NotFound',
        message: 'notification not found'
      }
      return render json: response, status: 404
    end

    if @notification.update(notification_params)
      render json: {
        status: 'Success',
        message: '',
        notification: @notification.as_json(except: [
          :created_at,
          :updated_at
        ])
      }, status: 201
    else
      response = {
        status: 'BadRequest',
        message: 'fail to update notification'
      }
      render json: response, status: 400
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:status)
    end
end

app/helpers/admin/notifications_helper.rb
module Admin::NotificationsHelper
end

app/views/admin/notifications/_form.html.slim
= form_with(model: [:admin, notification], local: true) do |form|
  - if notification.errors.any?
    #error_explanation
      h2
        = pluralize(notification.errors.count, "error")
        |  prohibited this notification from being saved:
      ul
        - notification.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :target_type
    = form.text_field :target_type
  .field
    = form.label :target_id
    = form.number_field :target_id
  .field
    = form.label :type
    = form.text_field :type
  .field
    = form.label :status
    = form.number_field :status
  .field
    = form.label :url
    = form.text_field :url
  .actions
    = form.submit

app/views/admin/notifications/edit.html.slim
h1
  | Editing Notification
= render 'form', notification: @notification
= link_to 'Show', [:admin, @notification]
|  | 
= link_to 'Back', admin_notifications_path

app/views/admin/notifications/index.html.slim
-if notice
  .alert.alert-primary role="alert"
    = notice
h1 通知
table.table
  thead.thead-dark
    tr
      th
        | Target type
      th
        | Target
      th
        | Type
      th
        | Status
      th
        | Url
      th[colspan="3"]
  tbody
    - @notifications.each do |notification|
      tr
        td
          = notification.target_type
        td
          = notification.target_id
        td
          = notification.type
        td
          = notification.status
        td
          = notification.url
        td
          = link_to 'Show', [:admin, notification], class: 'btn btn-primary btn-sm'
        td
          = link_to 'Edit', edit_admin_notification_path(notification), class: 'btn btn-light btn-sm'
        td
          = link_to 'Destroy', [:admin, notification], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

= paginate @notifications

app/views/admin/notifications/new.html.slim
h1
  | New Notification
= render 'form', notification: @notification
= link_to 'Back', admin_notifications_path

app/views/admin/notifications/show.html.slim
p#notice
  = notice
p
  strong
    | Target type:
  = @notification.target_type
p
  strong
    | Target:
  = @notification.target_id
p
  strong
    | Type:
  = @notification.type
p
  strong
    | Status:
  = @notification.status
p
  strong
    | Url:
  = @notification.url
= link_to 'Edit', edit_admin_notification_path(@notification)
|  | 
= link_to 'Back', admin_notifications_path